import Header from '@/components/navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { store } from "@/stores";
import { fetchUser } from "@/stores/user";
import { getProducts } from "@/stores/product";
import { getBasket } from "@/stores/basket";
import { StoreProvider } from '@/stores/provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
  await store.dispatch(fetchUser());
  const { user } = store.getState().user;

  await store.dispatch(getProducts());
  const { products } = store.getState().products;

  await store.dispatch(getBasket());
  const { basket } = store.getState().basket;

  console.log(basket)

  

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider
          preloadedState={{
            user: {
              user,
            },
            products: {
              products,
            },
            basket: {
              basket,
            },
          }}
        >
          <Header />
          {children}
        </StoreProvider>
      </body>
    </html>
  )
}
